# DigitalOcean App Spec for Donely
# Deploy: doctl apps create --spec .do/app.yaml

name: donely
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: Club-Prime/Donely
    branch: main
    deploy_on_push: true
  
  build_command: npm ci && npm run build
  output_dir: /dist
  
  # Environment variables for build
  envs:
  - key: NODE_ENV
    value: production
    scope: BUILD_TIME
  - key: VITE_SUPABASE_URL
    value: "https://mwtuixdmiahthqeswdqb.supabase.co"
    scope: BUILD_TIME
  - key: VITE_SUPABASE_PUBLISHABLE_KEY
    value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dHVpeGRtaWFodGhxZXN3ZHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTU3NjksImV4cCI6MjA3Mzg3MTc2OX0.KDDkP454yMNqylBf5e9Djyqd9F0hUd4g98ujS3qrmGc"
    scope: BUILD_TIME
  
  # SPA routing - all routes go to index.html
  routes:
  - path: /[^.]*
    type: rewrite
    target: /index.html
  - path: /

# Optional: Add alerts for monitoring
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED