// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwtuixdmiahthqeswdqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dHVpeGRtaWFodGhxZXN3ZHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTU3NjksImV4cCI6MjA3Mzg3MTc2OX0.KDDkP454yMNqylBf5e9Djyqd9F0hUd4g98ujS3qrmGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});