// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables provided by Vite for runtime configurability
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Configure your environment variables.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: {
      getItem: (key: string) => localStorage.getItem('donely-auth-token'),
      setItem: (key: string, value: string) => localStorage.setItem('donely-auth-token', value),
      removeItem: (key: string) => localStorage.removeItem('donely-auth-token'),
    },
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'implicit',
    detectSessionInUrl: false,
  },
  global: {
    headers: {
      'X-Client-Info': 'donely-app',
    },
  }
});